# Generated by Django 5.0.4 on 2024-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20),
        ),
    ]
